[package]
name = "grss"
version = "0.1.0"
authors = ["Patrizio Bertoni <pbertoni@x-next.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"

